spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: api1
          uri: lb://WELCOME-SERVICE
          predicates:
            - Path=/msg 

        - id: api2
          uri: lb://GREET-SERVICE
          predicates:
            - Path=/greet  

server:
  port: 3333
